steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['config', 'set', 'project', 'gcptestbed-270905']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', '. SimpleVM/test.sh']
- name: gcr.io/cloud-builders/gcloud
  args: ['deployment-manager', 'deployments', 'create', 'first', '--config=SimpleVM/createvm.yaml']
- name: gcr.io/cloud-builders/gcloud
  args: ['deployment-manager', 'deployments', 'list']