steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['config', 'set', 'project', 'fluent-archway-239902']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'ls -la']
- name: gcr.io/cloud-builders/gcloud
  args: ['deployment-manager', 'deployments', 'create', 'first', '--config=SimpleVM/createvm.yaml']
- name: gcr.io/cloud-builders/gcloud
  args: ['deployment-manager', 'deployments', 'list']